### ISSUE TITLE
gas-less Swap USDT for ETH - ERROR

### ISSUE THREAD

**Issue by SvenMeyer** [balancer-labs/frontend-v2#1094]
**Describe the bug**

Swapping 500 USDT for ETH results in ERROR

**To Reproduce**
1. Set Relayer Approval
2. Approve USDT spend limit (15000 USDT)
3. swap gas-less 500 USDT for ETH

result : ERROR message with no reason

```
sellToken: 0xdac17f958d2ee523a2206206994597c13d831ec7
buyToken: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
receiver: 0xc64ab................08bd68daed59ee
sellAmount: 435132232
buyAmount: 98260536789694117
validTo: 1637044266
appData: 0xe9f29ae547955463ed535162aefee525d8d309571a2b18bc26086c8c35d781eb
feeAmount: 64867768
kind: sell
partiallyFillable: false
sellTokenBalance: external
buyTokenBalance: erc20

```

### Firefox console

```
Unknown reason for bad order submission Request body deserialize error: invalid type: map, expected a u256 encoded as a decimal encoded string at line 1 column 672 instrument.js:109:45
    m instrument.js:109
    getErrorMessage OperatorError.ts:93
    getErrorFromStatusCode OperatorError.ts:113
    sendSignedOrder gnosisProtocol.service.ts:63
```

**Expected behavior**
should receive ~ 0.1 ETH

**Screenshots**

![image](https://user-images.githubusercontent.com/25609/141931887-08979dab-0623-4686-9639-5b2e4754c7ae.png)

![image](https://user-images.githubusercontent.com/25609/141932079-18a17d1a-3ad3-41ed-be45-eb99a0d133d6.png)

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
