### ISSUE TITLE
Shouldn't show stake/migrate button in Investment pools list

### ISSUE THREAD

**Issue by garethfuller** [balancer-labs/frontend-v2#1504]
**Describe the bug**
A stake button is currently shown in the Investment pools list when it shouldn't be. This list should be seen as a pool explorer and has nothing to do with the user's investments. There is no guarantee that the user is invested in any of these pools.

**To Reproduce**
1. Go to the home page
2. Connect wallet
3. Scroll to the Investment pools table
4. See stake/migrate column.

**Expected behavior**
The stake & migrate column should not be shown in the 'Investment pools' list.

**Screenshots**
<img width="1184" alt="Screenshot 2022-03-18 at 10 22 50" src="https://user-images.githubusercontent.com/2406506/158986453-28bc5dc4-a53e-4969-8f91-09f3d1724e38.png">

**Comment by 1saf** [comment]
Resolved.
