### ISSUE TITLE
My investments list should show stake column

### ISSUE THREAD

**Issue by garethfuller** [balancer-labs/frontend-v2#1505]
**Describe the bug**
It looks like the table column conditions are mixed up. The 'My V2 Investments' table has no 'Stake' column which it should if any of the pools are stakeable.

**To Reproduce**
1. Go to home page
2. Connect wallet
3. View My V2 Investments table
4. See that it doesn't have a Stake column

**Expected behavior**
The My V2 Investments table should show you which of your investments you can stake.

**Screenshots**
<img width="1239" alt="Screenshot 2022-03-18 at 10 33 23" src="https://user-images.githubusercontent.com/2406506/158987996-1f63764f-eac1-47e0-8d40-b7c7ad860810.png">

**Comment by 1saf** [comment]
Pon split this into an unstaked and staked pools table. But I can add it to both I guess?
