### ISSUE TITLE
Buttons text is scrambled / wrapped over itself

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1522]
**Describe the bug**
The 'Other Network' buttons have scrambled text on smaller screen sizes. Note, it's also happening in the header on the 'Connect' button where the icon has disappeared. 

**To Reproduce**
1. Go to the Claim page.
2. Scroll down to the 'Incentives on other networks' section. 
3. See the network buttons

**Expected behavior**
Normal unwrapped text

**Screenshots**

<img width="528" alt="Screen Shot 2022-03-22 at 11 14 11 PM" src="https://user-images.githubusercontent.com/1121139/159591496-8d4ccf00-382a-4df4-8137-7530a6a7af5b.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 13

**Comment by garethfuller** [comment]
@pkattera this should be fixed now. Please reopen if not.
