### ISSUE TITLE
Other Network claim button links look incorrect

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1523]
**Describe the bug**
It looks like the 'Incentives on other network' buttons link to '/claims' instead of '/claim'.

**To Reproduce**
1. Go to Claims page
2. Click on one of the claim buttons under the 'Incentives on other Networks' section. 

**Expected behavior**
For each network to link to the '/claim' route.

**Screenshots**

<img width="655" alt="Screen Shot 2022-03-22 at 11 20 09 PM" src="https://user-images.githubusercontent.com/1121139/159592055-5865de35-c022-4da5-91d9-2cea6c84efb9.png">

**Comment by evgenyboxer** [comment]
Fixed on branch
