### ISSUE TITLE
Stakable pool showing in both tables

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#1532]
**Describe the bug**
Maybe I'm looking at old designs, but IIUC in this case the BAL/USDC/WBTC pool should only be displayed in the My V2 Investments table with the stake button next to it, no?
![image](https://user-images.githubusercontent.com/34865315/159768966-75737ddd-a7c0-46c3-9016-f7706a1bfb52.png)

**Comment by garethfuller** [comment]
@markusbkoch this should be fixed. There are still cases where a staked pool can be in both tables though. e.g. You invest in a pool, stake that investment, then invest in the same pool again, but don't stake it.
