### ISSUE TITLE
Staked pools not counting to "My V2 Balancer investments"

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#1533]
**Describe the bug**
The value the user has in BPT that has been staked should count to their total $ amount in the banner

![image](https://user-images.githubusercontent.com/34865315/159769542-447c83f9-0a6f-4508-9c5a-f471a5ecf5e6.png)

**Comment by pkattera** [comment]
Note: This is related to issue #1535 

The value within veBAL should be displayed in the locked value of 80BAL/20WETH in the 'Unstaked pools' table.

**Comment by garethfuller** [comment]
This is also connected to #1559
