### ISSUE TITLE
Hardcode the list of pools/gauges that user can stake

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#1534]
**Describe the bug**
Anyone can create a gauge. I just created a gauge for the 80/20 pool and now the UI shows a call to action for me to stake that pool's token.
![image](https://user-images.githubusercontent.com/34865315/159771933-3e2344a9-61e7-4a70-8c31-9fd4db133a8c.png)
The frontend should have a list of pre-approved gauges so we're not inviting users to stake for nothing

**Comment by 1saf** [comment]
So are only intending whitelisted pools to be stakable?

**Comment by markusbkoch** [comment]
Yes. But keep in mind there may be temporary gauges that are only listed for a few weeks. When they are removed from the whitelist they should still be displayed as staked so that users can Unstake

**Comment by markusbkoch** [comment]
In other words, only invite users to skake on whitelisted gauges, but show all their staked pools regardless and allow them to Unstake from them

**Comment by garethfuller** [comment]
We should probably use the [hardcoded voting gauges list](https://github.com/balancer-labs/frontend-v2/blob/feature/tokenomics/src/constants/voting-gauges.ts) for this, right @markusbkoch? We can filter out voting gauges from other networks.

**Comment by markusbkoch** [comment]
@garethfuller We can use that but we need to complement it with ad-hoc gauges that will be incentivized with other tokens but no BAL, or only BAL from the 10% at the Baller's discretion.

**Comment by garethfuller** [comment]
@markusbkoch Ok then I don't think we should mix these up, we should have a separate liquidity gauge allowlist.
