### ISSUE TITLE
Treatment of 80BAL/20WETH in My Investments

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1535]
The 80BAL/20WETH pool cannot be staked. It can only be locked. This has some implications for the way it is displayed in the 'My Investments' section of the Invest page (or future Portfolio page):

- The 80BAL/20WETH pool can only appear in the unstaked table.
- A new CTA should be added to 'Lock' for the 80BAL/20WETH pool. This would apply if the lockable amount is greater than 0%.
- If it is locked 100%, replace the 'Lock' CTA with the text 'locked'.

_Example of an unlocked investment in 80BAL/20WETH pool:_

<img width="1073" alt="Screen Shot 2022-03-23 at 11 28 38 PM" src="https://user-images.githubusercontent.com/1121139/159813256-86b029b2-5095-4f6c-842f-43ef9e48de41.png">

_Example of an locked investment in 80BAL/20WETH pool:_

<img width="1069" alt="Screen Shot 2022-03-23 at 11 28 56 PM" src="https://user-images.githubusercontent.com/1121139/159813366-2d3736c0-d594-410b-bcd8-433591b8c381.png">

**Comment by garethfuller** [comment]
This was fixed by including the value of 80/20 locked in the hero.

**Comment by markusbkoch** [comment]
Reopening as I don't see the 80/20 in the "my unstaked pools" list if I've locked all of it into veBAL. Let me know if you prefer to handle in a new ticket.

**Comment by garethfuller** [comment]
@markusbkoch we decided to just show the vebal investment under the total for now, instead of injecting into the pools list. We can address this as part of moving these tables into the portfolio page.
