### ISSUE TITLE
'Add' buttons in the My veBAL stats section is missing when user has zero balances

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1536]
**Describe the bug**
The blue circular 'Add' buttons are currently not displaying if the user doesn't have any balances in the `My 80BAL-20WETH` or `My locked 80BAL-20WETH` containers. 

**To Reproduce**
1. Go to the Vote+Vest page with an empty wallet
2. View the stats section. 

**Expected behavior**
`My 80BAL-20WETH` and `My locked 80BAL-20WETH` containers should always have a `+` button which the user can click to get those LP tokens.

_Current behavior_

<img width="1589" alt="Screen Shot 2022-03-23 at 11 45 29 PM" src="https://user-images.githubusercontent.com/1121139/159816525-d86d6455-3f3d-4a8a-a2d2-a6d34e9bc84a.png">

_Expected behavior when user has a zero balance_

<img width="1203" alt="Screen Shot 2022-03-24 at 12 10 12 AM" src="https://user-images.githubusercontent.com/1121139/159816744-d2c339a8-2aee-4cee-8a99-f0294a1fccab.png">

**Comment by evgenyboxer** [comment]
Fixed on branch
