### ISSUE TITLE
Fix typo and formatting in the gauge voting screen

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1537]
There's currently a typo here and the warning container doesn't stretch full width:

<img width="881" alt="Screen Shot 2022-03-24 at 12 15 51 AM" src="https://user-images.githubusercontent.com/1121139/159817253-c0675b01-d68c-4595-a330-9f3bf2e76549.png">

**1. Text**  
Let's update the full text to be:

```
You need some veBAL to vote on gauges
Get veBAL by locking up LP tokens from the 80% BAL / 20% WETH pool.
```

**2. Formatting**

Add `w-full rounded` to the `bal-alert` div.

<img width="670" alt="Screen Shot 2022-03-24 at 12 19 17 AM" src="https://user-images.githubusercontent.com/1121139/159817895-f7e066f4-a3b9-4646-b94f-fb71679a0222.png">

This should get to:

<img width="434" alt="Screen Shot 2022-03-24 at 12 25 36 AM" src="https://user-images.githubusercontent.com/1121139/159818027-123b3949-215e-49e1-b6ef-5ff9725ff958.png">

**Comment by evgenyboxer** [comment]
Fixed on branch.
