### ISSUE TITLE
Include Staking button on the Invest confirmation screen

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1548]
Currently, at the end of the Invest flow, we don't offer the option to Stake the LP tokens. Let's provide users with the option to do so. 

**Solution**
At the Invest confirmation screen:
- If the pool is eligible for LM incentives: Add a new button, `Stake this to earn extra`. This should dismiss the current modal and trigger the same pop-up modal that happens when hitting the 'Stake' button on the Pool page.
- If the pool is not eligible for LM, keep the 'Return to pool page' secondary link as is.

<img width="1114" alt="Screen Shot 2022-03-24 at 9 32 00 PM" src="https://user-images.githubusercontent.com/1121139/160014188-1468ba55-e26f-42b9-89cf-ea155eadf3e6.png">

**Comment by evgenyboxer** [comment]
Done
