### ISSUE TITLE
Include 'Lock' button on the Invest confirmation screen for 80BAL/20WETH

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1549]
If the user adds liquidity to the 80BAL/20WETH pool - insert a button to 'Lock this to get veBAL'. This should link users to the `/get-vebal` route.

Note: This only happens for adding liquidity on the 80BAL/20WETH pool.

<img width="1065" alt="Screen Shot 2022-03-24 at 9 38 16 PM" src="https://user-images.githubusercontent.com/1121139/160015122-93da150d-86e0-446a-8bc5-9b995fc8f687.png">

**Comment by evgenyboxer** [comment]
Done
