### ISSUE TITLE
Mobile sidebar navigation is not working for primary nav items

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1563]
**Describe the bug**
In the new mobile sidebar, tapping the primary nav options (Invest, Trade, veBAL and Claim), changes the page behind the lightbox, but the lightbox remains visible and is not dismissed. 

**To Reproduce**
1. Open the mobile hamburger nav
2. Click on Invest / Trade / veBAL / Claim

**Expected behavior**
The sidebar should animate out, and the new page should be revealed. 

Seeing this on mobile and desktop.

**Comment by garethfuller** [comment]
Fixed here: https://github.com/balancer-labs/frontend-v2/pull/1519/commits/2a665900ef7a42b660d435548202607255527695
