### ISSUE TITLE
Tiny icon for the new tip on the veBAL page

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1564]
On small screens, the icon becomes tiny. 

Ideally the icon should have a fixed width or a minimum width. 

![IMG_922CBD35E9C7-1](https://user-images.githubusercontent.com/1121139/160262778-2aa16e89-080a-4ad8-a91b-aa52e5903fec.jpeg)

**Comment by garethfuller** [comment]
Fixed here: https://github.com/balancer-labs/frontend-v2/pull/1519/commits/ba96ac993df1848f5fe8e22bff176d7b890044f2
