### ISSUE TITLE
Lock preview modal immediately closes on `CREATE_LOCK` success

### ISSUE THREAD

**Issue by garethfuller** [balancer-labs/frontend-v2#1565]
**Describe the bug**
On tx confirmation of a lock creation the preview modal immediately closes. It should stay open with fireworks and link to etherscan. Weirdly, this doesn't happen for other lock types like extensions or increasing the amount.

**To Reproduce**
1. Go to lock page with no existing lock
2. Proceed to create a lock
3. Notice the modal close abruptly on success
4. Then, try going through the flow of adding more to that lock
5. Notice that the modal stays open as it should

**Expected behavior**
On lock creation success modal should stay open.

**Comment by garethfuller** [comment]
@evgenyboxer did you manage to merge in a quick fix for this? Could you work on making the state of the modal static?

**Comment by evgenyboxer** [comment]
Yeah I fixed it by moving the refetch to happen after the modal is closed

**Comment by evgenyboxer** [comment]
Fixed on dev
