### ISSUE TITLE
Error unwrapping ETH on Kovan

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1567]
**Describe the bug**
I get the following error when trying to unwrap ETH on Kovan. 

<img width="481" alt="Screen Shot 2022-03-27 at 8 56 04 PM" src="https://user-images.githubusercontent.com/1121139/160298464-1abac2da-64b9-4ee8-bbf5-610746649bff.png">

<img width="1073" alt="Screen Shot 2022-03-27 at 8 57 30 PM" src="https://user-images.githubusercontent.com/1121139/160298521-53edd2b1-b960-4e28-aa74-f77c5c6f1367.png">

**To Reproduce**
Go to Trade interface on Kovan and try to convert from WETH to ETH

**Expected behavior**
Successful trade. 

**Desktop (please complete the following information):**
Mac. Chrome. 99.0.4844.83

**Comment by TomAFrench** [comment]
This is expected as the WETH we use on kovan is a standard ERC20 token and doesn't contain ETH

**Comment by pkattera** [comment]
Got it. Closing the ticket.
