### ISSUE TITLE
L2 Staking incentives UI on Pool Page

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1568]
**Is your feature request related to a problem? Please describe.**

I understand that there is initially no 'staking' on L2s. Anyone who is in an eligible pool will receive LM incentives (without having to stake). Therefore, we need to change the UI slightly. 

**Spec**

1. Let's change the label from 'Staking incentives' to 'Liquidity mining incentives' across the board, for L1's and L2s.

2. If an L2 pool is eligible for LM incentives:

<img width="323" alt="Screen Shot 2022-03-27 at 9 01 29 PM" src="https://user-images.githubusercontent.com/1121139/160298644-98aa9d07-f2f0-4719-9741-d21876184145.png">

Text:

```
Liquidity mining incentives

People who invest in this pool receive liquidity mining incentives. Unlike on Ethereum Mainnet, no staking is required for eligible pools on [Polygon*].
```

* Ideally use the network that the user is on here.

**Comment by 1saf** [comment]
on it

**Comment by 1saf** [comment]
https://github.com/balancer-labs/frontend-v2/pull/1591
