### ISSUE TITLE
Add veBAL locking help text into an accordion.

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1572]
Let's place this content in an accordion which is compressed by default. 

<img width="1098" alt="Screen Shot 2022-03-27 at 10 33 08 PM" src="https://user-images.githubusercontent.com/1121139/160301956-ad819fa4-6de6-4750-ad15-e227dba7726e.png">

You may be able to use Ansaf's accordion from the 'Staking / Liquidity mining incentives' from the pool page. If so, remove the animating borders. You can see this accordion here: https://beta-kovan-git-feature-tokenomics-balancer.vercel.app/#/pool/0x647c1fd457b95b75d0972ff08fe01d7d7bda05df000200000000000000000001

**Comment by evgenyboxer** [comment]
Done
