### ISSUE TITLE
On Staking confirmation, add a button to view and claim staking rewards

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1573]
It's pretty powerful seeing rewards accumulating almost instantly. Let's give the user an option to view the 'Claim' page upon successfully staking. Like this:

<img width="949" alt="Screen Shot 2022-03-27 at 10 49 13 PM" src="https://user-images.githubusercontent.com/1121139/160302496-8a52328a-aa06-41ba-9a2a-c59d38bdf6d4.png">

**Comment by 1saf** [comment]
I think this change would best be for when APR is released @garethfuller thoughts?

**Comment by pkattera** [comment]
Actually, yeah, let's not push this today. Best to wait until emissions are live.

**Comment by pkattera** [comment]
Removed the on hold label. Let's get this done.
