### ISSUE TITLE
On Unstaked pool: Add 'N/A' to the Staking column for pools not eligible for LM

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1574]
**Describe the bug**

In the Unstaked Pools table, the table cell is currently empty for pools not eligible for LM. 
Let's add the text `N/A` for these pools. 

<img width="1269" alt="Screen Shot 2022-03-27 at 10 58 15 PM" src="https://user-images.githubusercontent.com/1121139/160302747-afcd757d-ef95-4bbe-a0db-dfb1b266767c.png">

**Comment by evgenyboxer** [comment]
Fixed
