### ISSUE TITLE
Error when staking LP tokens

### ISSUE THREAD

**Issue by FernandoMartinelli** [balancer-labs/frontend-v2#1585]
**Describe the bug**
Error msg when staking BPT

**To Reproduce**
1. Stake page
2. Click on "Stake" on the preview modal

**Expected behavior**
Metamask popup

**Screenshots**
![image](https://user-images.githubusercontent.com/1703258/160407353-f6f116a0-3db7-4809-816c-04e6536d6e5f.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave

**Additional context**
When I click the second time the expected behavior happens.

**Comment by 1saf** [comment]
Will be monitoring, but have been unable to recreate so far.

**Comment by garethfuller** [comment]
This is the same issue as #1687 and seems to be a more general issue.
