### ISSUE TITLE
Pools with gauges don't have a staking button on the main page.

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/frontend-v2#1595]
**Describe the bug**

Main page does not show a stake button for the GNO/COW pool despite it having a gauge and receiving COW/GNO rewards. The pool page does display the fact that there's a gauge however.

**To Reproduce**

Join the 50-50 COW-GNO pool and look at the main landing page and the pool invest page.

**Expected behavior**

A "stake" button should exist on the main landing page.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/15848336/160466586-4124b605-2abd-4c0c-9c15-fd0d6aa3aa61.png)

**Comment by garethfuller** [comment]
This should be fixed, please re-open if not. For future reference, stakeable pools need to be added to an allowlist.
