### ISSUE TITLE
Claim pages on Polygon/Arbitrum state that users will receive boosts

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/frontend-v2#1668]
**Describe the bug**

The text on the claim page says that users can boost their rewards by 2.5x if they have veBAL whereas they won't

**To Reproduce**
Go to https://arbitrum.balancer.fi/#/claim

**Expected behavior**
This text shouldn't promise boosts for users on Polygon/Arbitrum

**Screenshots**
![image](https://user-images.githubusercontent.com/15848336/162146456-0445c087-e381-491b-91ca-48c91c59cd89.png)

**Comment by pkattera** [comment]
Claim your liquidity mining incentives
The Balancer protocol and partners provide incentives to attract liquidity in eligible pools. 
Transition to new veBAL tokenomics
Liquidity mining incentives start on 7 April 2022 at 0:00 UTC. Earnings on Polygon and Arbitrum can be claimed weekly on Thursdays from 14 April. In the meantime, you can prepare by getting veBAL, providing liquidity, staking and voting on eligible pools.
