### ISSUE TITLE
Input underflow issue

### ISSUE THREAD

**Issue by FernandoMartinelli** [balancer-labs/frontend-v2#1687]
**Describe the bug**
Not possible to vote on gauge

**To Reproduce**
1. Try to vote on gauge

**Expected behavior**
Normal flow

**Screenshots**
<img width="469" alt="image" src="https://user-images.githubusercontent.com/1703258/162593096-0b0ae5a7-0206-49f7-a724-c32e1c46f18d.png">

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by FernandoMartinelli** [comment]
After I changed it to 49% it worked:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/1703258/162593119-6545f92f-bf92-4988-a0ba-42e41fa90d18.png">

**Comment by garethfuller** [comment]
Changing name of issue since it's more general than just voting.

**Comment by garethfuller** [comment]
Also seen here: #1585

**Comment by timjrobinson** [comment]
Fixed in #1803
