### ISSUE TITLE
New column 'Potential APR' in Unstaked Pools table

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1696]
Right now, user's who've added liquidity to eligible staking pools see their current APR but may not realize how much extra they could be earning by staking. 

**Describe the solution you'd like**

Add a new column for 'Potential APR' that is only displayed in the 'Unstaked pools' table. 
- If the pool is eligible for staking, add an APR range (see logic below). 
- If the pool is not eligible, the cell should read `N/A`
- If the pool is for the 80/20 BAL/WETH pool, just show a single number instead of the range (swap fee + 10%).

Logic for the APR range:
- The lower number in the range is based on what would be the user's current boost if staked. e.g. If based on the liquidity provided and their veBAL, what would their APR be? This must be >= 1.0x.
- The higher number should be <= 2.5x. Note: the max boost for a pool is not always 2.5x. If the user has a large share of the liquidity in a pool, the max boost will be less than 2.5x. In these cases, show the max boost for the user based on their liquidity size and veBAL holdings.

![New Potential APR column](https://user-images.githubusercontent.com/1121139/162765221-342ce9b7-1160-447b-b2c3-b328830cec9d.png)

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
