### ISSUE TITLE
Add new tooltips for the max boost in Staked pools

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1703]
**Is your feature request related to a problem? Please describe.**
Right now, user's can see their current boost but don't know how much veBAL they need to get their max theoretical boost. 

**Describe the solution you'd like**
Add tooltips on the 'My boost' numbers in the Staked Pools table, which allows users to see exactly how much veBAL they need to get the max boost.

**Describe alternatives you've considered**
A fully fledged boost calculator. 

**Additional context**
The theoretical max boost for stakers is 2.5x. However, this maximum cannot always be achieved. It's dependent on your stake size in the pool and the amount of veBAL other Stakers in the pool hold. We need to explain this via the UI, otherwise people may be confused why they can't get to 2.5x. 

**Designs**

<img width="1190" alt="My boost tooltip" src="https://user-images.githubusercontent.com/1121139/162940543-6c33ee21-dff0-49bf-bbc6-d3151c3fe72b.png">

**Spec**

_1. If the user's max theoretical max boost is >= 2.495_

- Round up to 2.5x
- Display the simpler tooltip without the additional explanation. 
- Sample text:

```
To get your max boost: 2.5x
You need 348.46 veBAL

B-80BAL-20WETH needed:
~$15,000 locked for 1 year
```

_2. If the user's max theoretical max boost is < 2.495_

- Display max theoretical max
- Display tooltip with the additional explanation
- Sample additional explanation text:

```
Your max theoretical boost is less than 2.5x due to the large size of your stake and the veBAL of other stakers in this pool.
```

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
