### ISSUE TITLE
Staking module – bottom padding broken on medium size screens 

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1710]
**Describe the bug**
On medium sized screens, when the text 'Potential weekly earnings' wraps, the bottom padding breaks.

**To Reproduce**
1. Go to a pool page that is eligible for liquidity mining
2. Resize browser

<img width="354" alt="Screen Shot 2022-04-13 at 10 56 08 PM" src="https://user-images.githubusercontent.com/1121139/163277343-252e2cf7-1b04-46e3-bcdd-59a14541f0bb.png">

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
