### ISSUE TITLE
Sort APR only work on first page

### ISSUE THREAD

**Issue by joeywongt3ch** [balancer-labs/frontend-v2#1719]
Bug report by user:

**Describe the bug**
Under investment, if sort pool by APR, it only sort the pools that are already loaded, not all pools. 

**To Reproduce**
1. Go to https://app.balancer.fi/#/
2. Under "investment pools", click on sort APR
3. See error, if compared to scroll down and clicking "load more".

**Expected behavior**
When sort by APR, it should sort all pools. Otherwise, some high APR pools are always be missed. 

**Screenshots**
![22-04-15-22-40-42-302_deco](https://user-images.githubusercontent.com/49179952/163585011-6f85df4c-6cc8-4968-b13e-36f62be48f7c.jpg)

**Smartphone (please complete the following information):**
 - Device: Nokia 8.1
 - Browser: metamask mobile

**Comment by markusbkoch** [comment]
This is unfortunately not possible with our existing backend, but might be something we could implement within the pools API - cc @timjrobinson @mendesfabio

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
