### ISSUE TITLE
Wallet presence indicator tooltip

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1735]
**Is your feature request related to a problem? Please describe.**
Right now, we have the wallet presence indictor which shows if a token is in the user's wallet. However, it's very subtle and needs more context.

**Describe the solution you'd like**
Add a tooltip when a user hovers, or focuses on a token pill with a wallet balance.

![Group 18](https://user-images.githubusercontent.com/1121139/164043881-adfb47a5-54cf-4499-823b-c9bbeb1d76c5.png)

**Comment by alter-eggo** [comment]
There may be issues with performance, due to multiple mouseenter/mouseleave event handlers. For example, if user has many tokens in wallet and loaded a lot of investment pools 🤔

**Comment by evgenyboxer** [comment]
Just sent a PR for this - https://github.com/balancer-labs/frontend-v2/pull/1753

Let me know if you encounter any perf issues.
