### ISSUE TITLE
Fee text for dynamically managed swap fees by the Ballers

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1748]
**Is your feature request related to a problem? Please describe.**
Now that the Ballers are managing dynamic swap fees on certain pools, user's need to be informed of this in a similar way to how we did this when Gauntlet was managing these fees.

**Describe the solution you'd like**

For all pools with dynamic swap fees managed by the Ballers, add this to the Pool page:

`Dynamic swap fees: Currently [X.XX]%` followed by the Ballers logo (attached)

<img width="753" alt="Screen Shot 2022-04-20 at 6 11 50 PM" src="https://user-images.githubusercontent.com/1121139/164286445-3b51d8d5-c036-4225-9c7f-3abf17d3e383.png">

Baller's logo:

![ballers-logo](https://user-images.githubusercontent.com/1121139/164286680-4996f365-c3e8-46bf-b7b8-1c9f42b5173e.png)

The Baller's logo should have a tooltip. Previously for Gauntlet, the text for this in default.json in `feesManagedByGauntlet` was:

```
"Liquidity providers earn dynamic swap fees on every trade utilizing the liquidity in this pool. Dynamic swap fees are controlled by governance and are currently set by Gauntlet.",
```

For the Ballers, update the text to:

```
"Liquidity providers earn dynamic swap fees on every trade utilizing the liquidity in this pool. Dynamic swap fees are controlled by governance and are currently set by the Ballers.",
```

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
