### ISSUE TITLE
Some invest notifications are not displaying the pool name

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1763]
**Describe the bug**

The invest notifications and recent activity items are not always displaying the pool name for investments.

**To Reproduce**
1. Add liquidity to a pool. 
2. Look at the notifications.
3. This might be hard to replicate because I don't think it happens every time. Recently happened on the reth/weth pool.

<img width="654" alt="Screen Shot 2022-04-21 at 10 04 02 PM" src="https://user-images.githubusercontent.com/1121139/164552186-f653ae90-1ee6-479b-8421-7b2b1316c6e2.png">

_In 'recent activity'_

<img width="536" alt="Screen Shot 2022-04-23 at 3 37 40 PM" src="https://user-images.githubusercontent.com/1121139/164910627-95f5b556-1898-445d-abc1-9d10d174b8f0.png">

**Expected behavior**

The notifications should show the pool name. If it doesn't know the pool name, remove the random `,` so that it just shows the investment amount.

_An example of one that displayed correctly:_

<img width="272" alt="Screen Shot 2022-04-21 at 10 01 49 PM" src="https://user-images.githubusercontent.com/1121139/164552595-aecc7ad7-aecf-40a6-8f52-6edb526d140d.png">

**Comment by garethfuller** [comment]
I think I fixed this when working on USD+ boosted pool support. Closing. Please re-open if seen again.
