### ISSUE TITLE
Flash of the 'no results' table on the claims page before real claims display

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1764]
**Describe the bug**
On the claims page, users who have liquidity mining incentives to claim, initially see the claims table say 'no results' after the pulsing loading animation, before it refreshes again to show the real results. 

**To Reproduce**
1. Stake and have veBAL
2. Go to claims page 
3. You'll see the 'no results' table display after the loading pulse animation before the table refreshes to show the real results.

**Expected behavior**
The real results should display after the loading animation. The user shouldn't see the 'no results' text.

**Comment by evgenyboxer** [comment]
Just tested this - I'm unable to reproduce.
Are you able to provide a short video?

I do see a different problem tho - it shows "no results" for unconnected wallet, then if connected it stays this way for a bit until the wallet is connected.

**Comment by pkattera** [comment]
@evgenyboxer Looks like we may be talking about the same issue with the unconnected wallet showing 'no results'. Here's the video: https://www.loom.com/share/1561a106758f4407844bdb7ed711f493

**Comment by pkattera** [comment]
This issue seems to have been fixed
