### ISSUE TITLE
Refresh claims every block and add a countup animation

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1765]
**Is your feature request related to a problem? Please describe.**
Claims amounts increase every block but the values don't update and require a page refresh. 

**Describe the solution you'd like**
To update the claim amount values dynamically so that the user's doesn't have to continually refresh the page.
Ideally, there should also be a simple countup animation of the value and amount fields every block.

A good reference is on https://matcha.xyz/markets/1/ETH –  watch the price update animations. The animation should take around 1s with an ease-out animation curve.

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
