### ISSUE TITLE
Invest in boosted Pools bug

### ISSUE THREAD

**Issue by joeywongt3ch** [balancer-labs/frontend-v2#1772]
**Describe the bug**
More than one users report cannot invest in boosted pools if using max. But no problems in other pools.

**To Reproduce**
1. Go to https://app.balancer.fi/#/pool/0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb20000000000000000000000fe
2. Click on 'max'
3. See error: keep loading, no price inpact shown, no preview clickable
4. Input small value in USDC
5. See error: high price impact

**Expected behavior**
Price impact small, preview clickable. Invest success.

**Screenshots**
![image (7)](https://user-images.githubusercontent.com/49179952/164975171-85c51eb3-d191-41ef-9214-9fae89d06915.png)
![image (5)](https://user-images.githubusercontent.com/49179952/164975174-b0c16d42-4bdd-40bd-822b-e4d4b6da33c3.png)

Smartphone:
Mobile metamask 
Android
Browser [chrome]

**Comment by garethfuller** [comment]
I can't replicate this on Kovan or Mainnet. It could be that these were temporary network issues because we have to simulate a batch swap via the SOR in order to calculate the price impact. If that request fails then it can cause problems. If complaints about this persist please re-open this issue.
