### ISSUE TITLE
High Price Impact for very small trades

### ISSUE THREAD

**Issue by timjrobinson** [balancer-labs/frontend-v2#1785]
**Describe the bug**
On both Polygon and Arbitrum the UI sometimes says a trade has a High price impact even when the amount is < $5. This isn't happening for larger trades. 

This appears to be happening because we have some unbalanced pools with really low liquidity, and so SOR will route through those pools when possible, but because the ratio is so different than the market price it says the trade is significantly moving the price. 

We could fix this by calculating the total liquidity available for a trade and if the amount being traded is < 1% (or smaller) of the total available liquidity then we never show the price impact warning. 

We are already calculating the total liquidity available here: https://github.com/balancer-labs/balancer-sor/blob/master/src/router/index.ts#L24 we would need to expose this to the frontend somehow. 

**To Reproduce**
1. Perform a trade on Polygon/Arbitrum with a very small amount of a common trade amount (I tried MATIC/ETH on Polygon and USDC/ETH on Arbitrum)

**Screenshots**
![2022-04-27-161525_509x594_scrot](https://user-images.githubusercontent.com/525534/165454037-491ebd27-657a-463c-84c0-dbe5cd6a94f8.png)

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
