### ISSUE TITLE
Remove 'veBAL' from Invest token filter options

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1787]
**Describe the bug**
Since veBAL can't exist in pools, it shouldn't be displayed in the user's wallet for filter options for the Investment pools table. Clicking it will always end up in zero results listed.

<img width="388" alt="Screen Shot 2022-04-27 at 9 35 46 AM" src="https://user-images.githubusercontent.com/1121139/165477324-4925b734-12ac-49d5-a809-e6179d40e1d1.png">

**To Reproduce**
1. Go to the Invest page with a connected wallet that holds veBAL
2. See the veBAL token appear in the wallet filter list

**Expected behavior**
veBAL should not appear

**Comment by timjrobinson** [comment]
Fixed in #1802
