### ISSUE TITLE
Can't extend veBAL lock after the original lock period has expired

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1795]
**Describe the bug**
After a locking period has expired, I'm not able to extend the lock period.

**To Reproduce**
1. Go to a veBAL wallet with an expired lock.
2. Try to extend the lock
3. See the error message

<img width="1227" alt="Screen Shot 2022-04-27 at 4 52 34 PM" src="https://user-images.githubusercontent.com/1121139/165587168-c2b0c64f-4801-4687-93bf-ddfff6bcc83f.png">

<img width="564" alt="Screen Shot 2022-04-27 at 5 09 43 PM" src="https://user-images.githubusercontent.com/1121139/165587649-37d8d40c-eba3-4901-bd07-8424c22ed7b5.png">

**Expected behavior**
To be able to enter an amount and lock up.

**Additional context**
Was tested on Kovan but sounds like it's an issue on Mainnet too.

**Comment by TomAFrench** [comment]
This is a limitation of the `VotingEscrow` contract .You need to withdraw the BPT and create a new lock.

**Comment by pkattera** [comment]
@TomAFrench We'll remove the 'plus' buttons here and only present the option to redeem expired tokens for these cases.
