### ISSUE TITLE
80/20 BAL pool is stakeable on Kovan despite not being on the allowlist

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1806]
**Describe the bug**

The 80% BAL / 20% WETH pool is currently stakeable despite not appearing on the allowlist.

https://kovan.balancer.fi/#/pool/0x61d5dc44849c9c87b0856a2a311536205c96c7fd000200000000000000000000

This may be indicative of a larger problem that could leak to mainnet.

**To Reproduce**
1. Add liquidity to the 80/20 BAL Pool 
2. Go to the [pool page](https://kovan.balancer.fi/#/pool/0x61d5dc44849c9c87b0856a2a311536205c96c7fd000200000000000000000000), and see the Staking module.

**Expected behavior**
This pool should not be stakeable and should not have a staking module on the pool page.

<img width="1189" alt="Screen Shot 2022-04-28 at 4 00 31 PM" src="https://user-images.githubusercontent.com/1121139/165782745-daa534f1-d633-4d9e-843b-c0606115996c.png">

**Comment by garethfuller** [comment]
Just want to add that this 80/20 pool on kovan isn't THE 80/20 pool used for locking. The reason this is an issue is because this pools ID is not included in the stakable allowlist and therefore shouldn't be stakable in the UI.

**Comment by garethfuller** [comment]
@pkattera I can't actually replicate this behaviour anymore. Not sure why this happened in the first place because I don't think has changed here. Please test again if you can and let me know if you see it.
