### ISSUE TITLE
New warning for veBAL gauge voting when 10% cap is exceeded

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1807]
**Is your feature request related to a problem? Please describe.**
Right now, people may be wasting their votes on the veBAL gauge since it gets capped to 10%.

**Describe the solution you'd like**
Add a new warning which informs the user that they may be wasting their vote. This should not disable the CTA.

![warning](https://user-images.githubusercontent.com/1121139/165785358-4871cff6-2a6e-4ee1-bd86-d08a25c618c2.png)

Text:

```
You may be wasting your vote: veBAL cap hit
Distributions to veBAL holders of weekly emissions are capped at 10%. Any votes exceeding this amount at Thursday 0:00 UTC will not be counted.
```

If it's too hard to calculate if the user's vote will tip the gauge over 10%, just show the warning if the cap > 10%.

**Comment by timjrobinson** [comment]
Fixed in #1815
