### ISSUE TITLE
Incorrect price impact calculation for boosted pool 

### ISSUE THREAD

**Issue by mikebmikeb** [balancer-labs/frontend-v2#1810]
**Describe the bug**
The deposit ui displays negligible price impact when depositing into the mainnet aave boosted pool.  

**To Reproduce**
Go to https://app.balancer.fi/#/pool/0x7b50775383d3d6f0215a8f290f2c9e2eebbeceb20000000000000000000000fe/invest
type in a billion for any of the tokens
price impact is 0.23% for a 1,000,000,000 deposit (more than there is in the entire pool) 
amp factor is 1472

**Screenshots**
<img width="481" alt="image" src="https://user-images.githubusercontent.com/90106964/165841437-858f0aa9-29ca-4d65-b32c-13511fd22067.png">

**Additional context**
It occurred to me that a pool with a high enough amp factor could possibly have these sort of price impacts but its only 1472 on this pool

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
