### ISSUE TITLE
Output value disappearing when output gets too large on polygon trade ui

### ISSUE THREAD

**Issue by mikebmikeb** [balancer-labs/frontend-v2#1811]
**Describe the bug**
A bit hard for me to explain this in words, video below.  the output value disappears under certain conditions, perhaps when it has to route through multiple pools?  (Can't see routing prior to trading anymore) 
This does not happen if you manually type the output.  

**To Reproduce**
1. Go to polygon trade interface
2. input: matic output: usdc
3. type in 2000 matic as input, the trade will route properly.  input 20000, the trade will route correctly for a brief moment, then the output will disappear

**Screenshots**
video:
https://user-images.githubusercontent.com/90106964/165843233-a116d28d-cda1-48f1-9b5d-10c3dff3f34f.mov

with input as 2000
<img width="490" alt="image" src="https://user-images.githubusercontent.com/90106964/165843672-897856de-8aba-4ed4-b024-809a16f99e37.png">

with input as 20000
<img width="502" alt="image" src="https://user-images.githubusercontent.com/90106964/165843708-1237871c-1ca3-4f71-9814-6d31dee129da.png">

**Expected behavior**
The output value should not disappear.

**Comment by timjrobinson** [comment]
Fixed in 1819
