### ISSUE TITLE
Values get messed up when swapping input/output

### ISSUE THREAD

**Issue by mikebmikeb** [balancer-labs/frontend-v2#1812]
**Describe the bug**
When using the "swap input/output" button on the trade ui 
<img width="101" alt="image" src="https://user-images.githubusercontent.com/90106964/165842536-f00a8f8f-1086-43c8-8c29-5544fd358273.png">
the values get buggy when the above button is clicked while there are inputs filled in.

**To Reproduce**
1. go to the trade interface on polygon
2. put input as usdc, output as link
3. input 20 link as output value
4. click the "swap input/output" button

**Expected behavior**
the amounts should not go into the 

**Screenshots**
Prior to clicking the button 
<img width="520" alt="image" src="https://user-images.githubusercontent.com/90106964/165843974-e43650c9-e2f7-411a-939c-3187834bb4c8.png">

clicking the button twice
<img width="459" alt="image" src="https://user-images.githubusercontent.com/90106964/165844048-a712ddb5-ec99-4c3f-b653-95ed00a2dd68.png">

clicking it a third time 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/90106964/165844083-b5dd4953-1975-41d6-a08b-0eab13047a00.png">

**Additional context**
Seems to not be 100% consistent, but if you click the swap input/output button a couple times it will definitely trigger it.

I theorize this has something to do with usdc's 6 decimal places since i can't get similar behavior from other tokens

**Comment by ThannDev** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by timjrobinson** [comment]
Fixed in #1819
