### ISSUE TITLE
[feature request] Bring back the ability to see trade routing without needing to bring up the modal

### ISSUE THREAD

**Issue by mikebmikeb** [balancer-labs/frontend-v2#1813]
**Is your feature request related to a problem? Please describe.**
A recent UI update moved the trade routing visual to the transaction modal, which is not accessible if you do not have enough tokens in your wallet.  

<img width="498" alt="image" src="https://user-images.githubusercontent.com/90106964/165846071-c814ba07-4b6b-4022-b46f-0286ce8fe097.png">

the trade routing visual:
![image](https://user-images.githubusercontent.com/90106964/165844873-c91a4ae7-323f-465e-aeb9-9d85413c5956.png)

**Describe the solution you'd like**
I think the trade routing should be listed on the trade screen without needing to click the preview button, since it cannot be done unless you have the tokens in your wallet.  This is how it was not too long ago and beethovenx has it how I would like it
<img width="488" alt="image" src="https://user-images.githubusercontent.com/90106964/165845483-ba371470-255e-4cf0-b26b-eb436be957c0.png">

**Describe alternatives you've considered**
If you inspect the preview button and delete the disabled attribute on the preview button, you can force open the modal and see the trade routing.  I don't feel like I should have to do this though.

**Additional context**
Seeing trade routing is important for debugging issues and analyzing how the SOR practically routes certain trades through available balancer pools.  I think putting this feature into the modal has removed a lot of utility of the feature.  

Curious as to how others feel about this.

**Comment by garethfuller** [comment]
@mikebmikeb this is possible now but it's kind of an advanced hidden feature. Just set a local storage variable in your browser `alwaysShowRoutes` to true.
