### ISSUE TITLE
Remove gap in the token select modal

### ISSUE THREAD

**Issue by alter-eggo** [balancer-labs/frontend-v2#1818]
**Describe the bug**
There is a gap at the bottom of token select modal on short/medium size screens because of hardcoded `height: 24rem`.

**Screenshots**
<img width="1709" alt="Screenshot 2022-05-01 at 17 56 41" src="https://user-images.githubusercontent.com/46521087/166151696-7d20910b-1b24-45dc-94b8-3e5eded53a99.png">

**Smartphone:**
Devices with width less than 640px.

**Comment by insulineru** [comment]
Hi, @alter-eggo. Please check my pull request, i fixed this bug

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
