### ISSUE TITLE
Reward estimates on staking page don't take veBAL into account

### ISSUE THREAD

**Issue by timjrobinson** [balancer-labs/frontend-v2#1838]
**Describe the bug**

Minor issue - when you go to stake LP tokens it always shows the minimum staking rate, not the boosted staking rate. See screenshots, these were taken straight after each other. 

This is a minor issue as people will be happy that their rewards are greater than what it said initially, but it may make people not stake if they think they're not getting any boost. 

If it's not meant to apply the boost on the stake screen, or if we can't calculate it, it should say "Min Staking APR" instead of "Your Staking APR". 

**Screenshots**

Staking lock screen says my staking APR is 14.55%, which is the minimum:

![2022-05-06 12_21_31-Balancer](https://user-images.githubusercontent.com/525534/167056674-4d64d7b5-b9d4-4d53-bf0b-d1340add9760.png)

After staking it shows my real APR on the pools table, with the 2.49x boost:

![2022-05-06 12_23_22-Balancer](https://user-images.githubusercontent.com/525534/167056746-2a4d465c-2c59-49cd-a032-771702f53e5f.png)

Pool after staking, showing correct weekly earnings:

![2022-05-06 12_27_41-Balancer](https://user-images.githubusercontent.com/525534/167056864-cf6304b5-cc81-4af0-8c7a-2ddc640bab50.png)

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
