### ISSUE TITLE
Show user's APR info in pool page

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#1843]
APR info in the pool page should be the user's, not the range.
![image](https://user-images.githubusercontent.com/34865315/167155018-a2b42f1b-46b5-448d-875b-a5d76e46fff2.png)

Like in the my investments table, where it takes the boost into account so as to display a single value.

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
