### ISSUE TITLE
Account for staked BPT in "my pool balance" card inside invest flow

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#1845]
The "my pool balance" card in the pool page accounts for staked BPT. But once the user enters the invest flow, the equivalent card there does not. Minor issue, but for consistency it should.

![image](https://user-images.githubusercontent.com/34865315/167155730-59b3f4b2-429b-4ba0-bbcc-8b7848af038b.png)

**Comment by garethfuller** [comment]
@sssmi maybe you could look into this when you have time to work on an issue.
