### ISSUE TITLE
Incorrect "Min staking APR" in APR card

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#1846]
The "Min staking APR" entry should be the sum of "Min BAL APR" and "Rewards APR" entries
![image](https://user-images.githubusercontent.com/34865315/167156322-79b2a183-db89-4248-af89-fdfac8df8fac.png)

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
