### ISSUE TITLE
[Feature Request] Alternate currencies on investments overview

### ISSUE THREAD

**Issue by ElianCodes** [balancer-labs/frontend-v2#1864]
It's kind of annoying to non-Americans to only be able to use Dollar as a main currency on the Invest tab (see screenshot below)

<img width="855" alt="Screenshot 2022-05-12 at 22 01 00" src="https://user-images.githubusercontent.com/15145918/168158413-9c038e7a-aaac-4657-8a76-2a419edc7077.png">

Maybe it would be a good feature to be able to select a main fiat currency like euro or dollar, or even a secondary like value in BTC or ETH. (as seen below)

<img width="856" alt="Screenshot 2022-05-12 at 22 01 55" src="https://user-images.githubusercontent.com/15145918/168158569-ec3d4472-3eaa-4a37-94e5-cca108a09c81.png">

<img width="857" alt="Screenshot 2022-05-12 at 22 02 33" src="https://user-images.githubusercontent.com/15145918/168158668-6c27ddfa-0320-458d-a742-32d9a2965ff0.png">

Maybe even a combination of both as below could be possible interesting feature?

<img width="855" alt="Screenshot 2022-05-12 at 22 05 29" src="https://user-images.githubusercontent.com/15145918/168159060-967ef7ef-9b93-40d5-b4a1-e9c5e666c54d.png">

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
