### ISSUE TITLE
Incorrect Potential Earnings amount in Staking Preview

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1908]
**Describe the bug**

Currently, in the Staking preview, the user sees 'Your staking APR' and 'Potential weekly earnings'. However, these amounts are incorrect because they don't include the boosted rates. 

In the screenshots below, while staking the stETH pool, this preview modal appeared while Staking :

![image (4)](https://user-images.githubusercontent.com/1121139/169293835-3d9537b0-9fe7-4415-bb5d-ca9e8147f6e2.png)

But, straight after staking, the user gets a different number in the Staked pools table on the Investments page.

![image (5)](https://user-images.githubusercontent.com/1121139/169293925-2e581d44-ca2b-48de-a446-adc41b449e48.png)

It’s really confusing to show a wrong expected amount if we show the right one right after the action is done. Since the user sees a much smaller number in the Staking preview, they may also choose not to do the transaction which is costing Balancer TVL

**To Reproduce**
1. Get veBAL
2. Stake into an eligible pool
3. View preview modal numbers.
4. Complete the transaction and view the numbers in the Staked Investments table.

**Expected behavior**

<img width="429" alt="Screen Shot 2022-05-19 at 1 40 04 PM" src="https://user-images.githubusercontent.com/1121139/169295363-ad66df85-97a3-4a4d-b6cd-316c331ca243.png">

1. Add a new line for `My potential boost`
2. Include the boosted rate into the `My boosted staking APR` number
3. Include the boosted rate into the `Potential weekly earnings` number

**Comment by garethfuller** [comment]
@pkattera for now I'm just going to have to remove the 'My potential boost' and 'My boosted staking APR' rows. There is a bit of work to get the data for these calculations and there are higher priorities atm, unfortunately. Let me know if you don't agree with hiding them for now.

**Comment by timjrobinson** [comment]
Also raised here: #1830

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
