### ISSUE TITLE
Re-introduce locales

### ISSUE THREAD

**Issue by garethfuller** [balancer-labs/frontend-v2#1953]
As part of bundle optimisation we're removing non-english locale files. When we come to add a locale picker feature we should start by re-introducing these files since they contain some adjustments by human translators. These translations were removed at this commit: https://github.com/balancer-labs/frontend-v2/pull/1944/commits/2f5884d9d6af530ce67e31ba754db538d0a0026e

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
