### ISSUE TITLE
Add 'expired' states for expired pool gauges

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1959]
**Is your feature request related to a problem? Please describe.**
Currently, there are some pools in the Balancer ecosystem which expire. For example, some of the Element Finance pools. The problem is that people may still vote for these expired pool gauges. 

<img width="535" alt="Screen Shot 2022-06-08 at 11 16 10 AM" src="https://user-images.githubusercontent.com/1121139/172593609-f135dc19-a386-40da-83f5-fe64685524ae.png">

**Describe the solution you'd like**

1. On the veBAL page, add new expired styles on rows which contain an expired pool.
2. Add a new bg-red-500 'Expired' pill at the end of the token symbol pills. 
3. To differentiate 'New' pools from 'Expired' pools, change the color of the 'New pill' - `bg-yellow-500` with `text-black`

If the user has a connected wallet & the wallet has not allocated any votes to this pool:
- Disable the vote button.

If the user has a connected wallet & the wallet has allocated any votes to this pool:
- Set the color of their vote allocation to `text-red-600 dark:text-red-500`
- Include a new button titled 'Remove'. This button will pop up the same voting modal but allow the user to set their vote back to 0. 

**Additional context**

![Slice 1](https://user-images.githubusercontent.com/1121139/172595057-c06f8821-8cbe-47ad-829f-009de092919d.png)

In Figma: https://www.figma.com/file/ck02ERXjdBEmPOIfmltmW8/Tokenomics?node-id=2591%3A32201

**Comment by garethfuller** [comment]
For implementation, to check if a gauge has expired we should be calling `is_killed` on the gauge contract.

**Comment by pkattera** [comment]
This has been completed.
