### ISSUE TITLE
Use Tailwind Eslint Plugin

### ISSUE THREAD

**Issue by insulineru** [balancer-labs/frontend-v2#1978]
**Is your feature request related to a problem? Please describe.**

I was a little confused by the way you group classes in your project through arrays and the dynamic value `:class`.

**Describe the solution you'd like**

I suggest to use [eslint-tailwind-plugin](https://www.npmjs.com/package/eslint-plugin-tailwindcss) which will allow to automatically sort classes, facilitate migration to tailwind 3 (which I am doing at the moment) and fix existing code (like repeated classes, reused properties, etc)

If you don't mind - let me make this Pull Request 😉

**Comment by insulineru** [comment]
@garethfuller @markusbkoch @1saf @pkattera I apologize for the unnecessary mentions, but without your help I can't put labels and mention contributors for discussion, so please note this issue

**Comment by pkattera** [comment]
Hi @insulineru – Gareth is currently out so the best person to provide feedback here is @timjrobinson or @1saf

**Comment by timjrobinson** [comment]
@insulineru Sure happy to accept PR's to upgrade to tailwind 3 and use that plugin, that's quite helpful. I'll review them as soon as I can.

**Comment by sssmi** [comment]
Tailwind plugin was added in #2092
