### ISSUE TITLE
Entries in the main pool table display the wrong tokens on loading more pools.

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/frontend-v2#1983]
**Describe the bug**

On the main page, if we click "load more" we get a number of pools having the wrong tokens listed resulting in certain pools seeming to appear twice (clicking on a duplicate pool will lead to a different pool page than you would expect based on the tokens displayed).

**To Reproduce**
1. Go to app.balancer.fi
2. Click on "Load more" on the pools table
3. See error

**Expected behavior**

Each pool should be listed once and display the correct tokens.

**Screenshots**

![image](https://user-images.githubusercontent.com/15848336/173676486-6daf5fe0-b075-47c9-8979-aaa71f699c24.png)

Here we can see a USDC-WETH stable pool (in reality it's the wstETH- WETH metastable pool), two versions of the OHM tri-pool. 2 Akita LBPs, etc.

**Comment by pkattera** [comment]
@TomAFrench I'm not able to replicate this. See anything strange here? https://www.loom.com/share/36026df0957b4542bc670641b2412a7e

**Comment by TomAFrench** [comment]
I was getting this very consistently but tried this on another computer and I get the same as you. Looks like it's caused by something local and clearing the cache/hard reset fixed it. Thanks Pon :)
