### ISSUE TITLE
Remove 'load more' bottom table row button when less than 10 results

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#1989]
**Describe the bug**
The table row containing the 'load more' button should be removed when there are less than 10 results in paginated tables, like the 'Investment pools' table. 

**To Reproduce**
1. Go to the home page
2. Filter by tokens / select a few popular tokens until there are less than 10 results
3. See the load more table row still visible.

**Expected behavior**
The table row should be completely removed.

**Screenshots**

See load more table row still present with less than 10 results.

![load-more](https://user-images.githubusercontent.com/1121139/173782051-38bc330b-389a-4076-8c63-3a27ecbe699c.png)

**Comment by vishesh0123** [comment]
can I work on this issue..

**Comment by garethfuller** [comment]
@vishesh0123 yeah sure!

**Comment by nayane95** [comment]
May I also try to fix this?
