### ISSUE TITLE
Choosing "ETH" in the invest modal breaks the ui

### ISSUE THREAD

**Issue by mikebmikeb** [balancer-labs/frontend-v2#1993]
**Describe the bug**
When you are depositing into a pool and select ETH instead of weth, the ui disappears.  

**To Reproduce**

1. https://app.balancer.fi/#/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014/invest go to here
2. Click on WETH and change it do ETH

**Expected behavior**
The ui should not disappear.  

**Screenshots**
<img width="553" alt="image" src="https://user-images.githubusercontent.com/90106964/174069909-f719a3be-22f5-4cf3-8065-b3cc687abcd5.png">

**Comment by timjrobinson** [comment]
Fixed with #1995
