### ISSUE TITLE
Add a lock module to the BAL 80 / WETH 20 pool

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#2030]
**Is your feature request related to a problem? Please describe.**

Currently, there is no locking module on the BAL 80 / WETH 20 pool. Ideally, we should have a similar module to the 'Staking' module present on all the staking pages. This can also present some actionable 'lock' items, or provide context on expired locks.

**Describe the solution you'd like**
- Add a new lock module on the BAL 80 / WETH 20 page
- Cater for some of the different state, including to handle expired locks (as per the screenshot)

**Additional context**

![lock-module](https://user-images.githubusercontent.com/1121139/176502887-2971e419-5c62-429b-bca5-c3a18003f769.png)

**Comment by 1saf** [comment]
Ill tackle this

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
