### ISSUE TITLE
Failed invest transactions: Value out of bounds

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#2054]
**Describe the bug**
While trying to invest small amounts, I get this error on Ethereum Mainnet:

```
Transaction failed
value out-of-bounds (argument=null, value={"type":"BigNumber","hex":"-0x0310c9c23a42e565"}, code=INVALID_ARGUMENT, version=abi/5.4.1) Please try again later.
```

Console error:

<img width="1245" alt="Screen Shot 2022-07-05 at 10 24 55 AM" src="https://user-images.githubusercontent.com/1121139/177296324-7d7f69c2-19e8-4c56-a243-9eade9d30d60.png">

**To Reproduce**
1. Go to Invest on Mainnet with a small amount – try this pool: https://app.balancer.fi/#/pool/0xa6f548df93de924d73be7d25dc02554c6bd66db500020000000000000000000e/invest
2. Invest a small amount - I did a single sided add and hit the preview button.
3. Then hit invest.

**Expected behavior**
No error and wallet pop up.

**Screenshots**

<img width="543" alt="Screen Shot 2022-07-05 at 10 22 25 AM" src="https://user-images.githubusercontent.com/1121139/177296774-ed29d6a2-407c-4845-ba4a-5fd4c838d50a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 103.0.5060.53

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
