### ISSUE TITLE
Unlisted reward tokens not accounted in APR

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#2076]
A few days ago we merged [this](https://github.com/balancer-labs/frontend-v2/pull/2068) and it fixed the issue where no APRs where displayed in the main page. But later Coingecko added SD's address and its APR would still not show in the UI, contrary to what I expected. So I realized the issue was probably the tokenlist, and adding SD to the assets repo fixed it.

I think we should not restrict reward tokens to allowlisted tokens. It might be unlikely in practice, but in theory it's possible that we don't "trust" token A and **want** to display warnings about it on the pages of the pools containing token A; but **we'd be ok** with that token being distributed to LPs. So there's a case to be made for **not** mixing up those two concepts into a single list.

**To Reproduce**
1. Pick a token that has a coingecko price feed and is not in the Balancer tokenlist
2. Add some amount of this token as a secondary reward to a gauge
3. APR for the pool doesn't take the token into account

**Expected behavior**
APR for the pool should take the reward token into account

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
