### ISSUE TITLE
Incorrect use of $ sign in pair prices

### ISSUE THREAD

**Issue by skyminert** [balancer-labs/frontend-v2#2149]
On the "Trade" screen here: https://app.balancer.fi/#/trade

The UI shows:
The token pair price of your chosen tokens pulling data from Coingecko

![image](https://user-images.githubusercontent.com/57817726/185180321-adcb68b0-8cf4-4921-9880-978767114812.png)

However, it shows the pair price with a "$" sign.  This is incorrect.  the number is not a $ amount.

**Comment by FernandoMartinelli** [comment]
Thanks for catching this @skyminert!

**Comment by skyminert** [comment]
no problem!
