### ISSUE TITLE
Add a new timelock icon for locked votes

### ISSUE THREAD

**Issue by pkattera** [balancer-labs/frontend-v2#2164]
**Is your feature request related to a problem? Please describe.**

After a user votes on a pool gauge, their vote is locked for 10 days. Currently we don't provide an indication of this to users. 

Note: We already do have logic to show users an alert message when they try voting on a pool under timelock – see below:

<img width="496" alt="Screen Shot 2022-08-22 at 6 10 42 PM" src="https://user-images.githubusercontent.com/1121139/185980127-437e8f9e-312b-4057-893d-036b474905ec.png">

**Describe the solution you'd like**

- Display a timelock icon (attached below) next to the user's vote on any pool gauge which is currently vote locked. 
- User votes can also expire. If a user's veBAL has expired and the vote is also under a timelock, display the expiry icon instead of the timelock icon. 
- Include a tooltip on hover and focus + tap on touch screens . Tooltip text:

```
**Votes cannot be edited within 10 days**
Votes on each pool gauge are locked for a 10 day period after the original vote. You can edit this pool vote anytime after 15:45 UTC on May 14 2022.
```

**Additional context**

<img width="1433" alt="Screen Shot 2022-08-22 at 6 41 47 PM" src="https://user-images.githubusercontent.com/1121139/185985074-8c7824cb-053f-481c-a9b4-4eb2372eeb44.png">

<img width="353" alt="Screen Shot 2022-08-22 at 6 39 35 PM" src="https://user-images.githubusercontent.com/1121139/185984896-a0de6e8d-393d-429a-9890-9619f51d92a1.png">

Timelock icon should be displayed at 20px x 20px and is attached.

The color of the icon should be `text-secondary` – which is `text-gray-600 dark:text-gray-400;` 

**Timelock SVG asset to use:**

![timelock](https://user-images.githubusercontent.com/1121139/185986641-b7195164-1f7c-4d64-beb7-3951c6bb6519.svg)

**Comment by sssmi** [comment]
Is this done?

**Comment by garethfuller** [comment]
I don't think so, @pkattera ?

**Comment by garethfuller** [comment]
@pkattera going to close this, please re-open if you think we haven't addressed this fully.

**Comment by pkattera** [comment]
Yes, this was completed. 

<img width="372" alt="Screenshot 2022-12-20 at 2 13 32 PM" src="https://user-images.githubusercontent.com/1121139/208687039-ac519a29-763f-46a7-8f35-a2eca798f29c.png">
