### ISSUE TITLE
Re-add pool total liquidity column to portfolio tables

### ISSUE THREAD

**Issue by garethfuller** [balancer-labs/frontend-v2#2212]
At some point in the past we had a 'Pool value' column on the portfolio page tables just like we do on the home page. We removed it to make room for more data that we never ended up adding. We should re-add the 'Pool value' column because it's a helpful context for users.

**Comment by AdwitiyaMishra** [comment]
Hi @garethfuller, I would like to work on this issue. It'd be great if you could assign it to me.
