### ISSUE TITLE
Pool pages should assume mainnet if no slug provided

### ISSUE THREAD

**Issue by garethfuller** [balancer-labs/frontend-v2#2368]
**Describe the bug**
Existing links to pool pages should still work. For example, `https://beta.balancer.fi/#/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080` should always link to the mainnet pool. Otherwise a whole bunch of external links to pool pages are going to break. At the moment if the current network happens to be polygon and you follow this link it will inject `polygon` into the path. Instead if the network slug doesn't exist and it's a pool page we should be resetting the network as mainnet and injecting the `ethereum` slug.

**To Reproduce**

1. Go to https://beta.balancer.fi
2. Switch network to polygon.
3. Close that window and then try and access this mainnet pool: https://beta.balancer.fi/#/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080
4. See pool not found error.

**Expected behavior**
If no network slug provided, pool pages should assume ethereum mainnet and change the network.

**Comment by garethfuller** [comment]
Essentially:
This: https://beta.balancer.fi/#/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080
Should always redirect to
This: https://beta.balancer.fi/#/ethereum/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080

Regardless of the user's last network selection.

**Comment by Matthews3301** [comment]
https://github.com/balancer-labs/frontend-v2/pull/2369
