### ISSUE TITLE
Vebal L2 modal redirect doesn't work

### ISSUE THREAD

**Issue by garethfuller** [balancer-labs/frontend-v2#2384]
**Describe the bug**
Sometimes the modal that pops up when you try to access the vebal page from a L2 doesn't work. When you click the 'proceed' link it changes the URL path but doesn't close the modal or load the vebal page. See Loom.

**To Reproduce**

1. Go to the vebal page on mainnet
2. Change your network to polygon
3. Click proceed in the modal
4. Nothing will happen, but URL will change.

**Expected behavior**
Clicking proceed in the modal should close the modal and reload the vebal page on mainnet.

**Visual context**
https://www.loom.com/share/fc68bf6eece04640bcb5c951a344dc8b

**Comment by Matthews3301** [comment]
https://github.com/balancer-labs/frontend-v2/pull/2387
