### ISSUE TITLE
Incorrect price impact for Composable stable pool on deposit

### ISSUE THREAD

**Issue by maciej-kozuszek** [balancer-labs/frontend-v2#2558]
![image](https://user-images.githubusercontent.com/92723862/207377075-32078e7a-e244-481a-9513-bec4d8929e2c.png)
Depositing Tokens to [this](https://app.balancer.fi/#/goerli/pool/0x3d5981bdd8d3e49eb7bbdc1d2b156a3ee019c18e0000000000000000000001a7) Composable Stable pool on goerli test network shows price impact equal to `0.00%` which seems to be incorrect - it should be at least `< 0.01%`

Steps to reproduce:
Since those are custom tokens we can obtain them by depositing single token (let's say USDC) and do proportional withdraw. Now we can deposit pool tokens.

Expected result:
Price impact should be either `< 0.01%` or any other value except `0.00%`

**Comment by garethfuller** [comment]
This is very likely something to do with Goerli and the specific pool composition here. If you can recreate this issue with a production network pool please re-open.
