### ISSUE TITLE
Delegate owner displays as regular address in Pool Details

### ISSUE THREAD

**Issue by EndymionJkb** [balancer-labs/frontend-v2#2609]
This is arguably a minor bug (potentially misleading UX), but I'm suggesting an alternative, so I suppose it's more of a feature request.

Every pool has an owner, which might either be a real address (e.g., an EOA or multisig), or the "delegate owner". While this has the address type, it's really a sentinel value meaning "check with the Vault's authorizer for all permissioned functions": not a real address. (Whereas an "owned" pool would allow the owner to perform certain operations, delegating any others to the Authorizer.)

Yet in Pool Details, it's displayed like a real address, with a link to a blank Etherscan page that could be misleading if you don't know what's happening. Maybe it could say "Delegate Owner", with a link to the relevant part of the docs explaining permission delegation?

Same with the zero address - those pools effectively have no owner: they don't support any owner-only admin functions (e.g., changing swap fees). This is also displayed like a normal address, though going there in Etherscan isn't very informative.

Navigate to the pool, and look at "Pool Owner" in "Pool Details"

Zero owner pool: http://app.balancer.fi/#/ethereum/pool/0x32296969ef14eb0c6d29669c550d4a0449130230000200000000000000000080

Delegate owner pool:
https://app.balancer.fi/#/ethereum/pool/0xa13a9247ea42d743238089903570127dda72fe4400000000000000000000035d

**Comment by garethfuller** [comment]
@alter-eggo could you handle this? It should be a very easy change. If the pool owner is `0x0000000000000000000000000000000000000000` or `0xBA1BA1ba1BA1bA1bA1Ba1BA1ba1BA1bA1ba1ba1B` display pool owner as "Delefate owner" with a link to the documentation.

@EndymionJkb Sorry it's taken so long to get to this. Do you know of the documentation where this is explained? I can't find anything.

**Comment by alter-eggo** [comment]
hm, if it is Zero address, we should display as "Delegate owner"?

may be `Zero owner`?

**Comment by garethfuller** [comment]
No the point is that ownership is delegated to the zero address, which is technically owned by no one.

**Comment by EndymionJkb** [comment]
> @alter-eggo could you handle this? It should be a very easy change. If the pool owner is `0x0000000000000000000000000000000000000000` or `0xBA1BA1ba1BA1bA1bA1Ba1BA1ba1BA1bA1ba1ba1B` display pool owner as "Delegate owner" with a link to the documentation.
> 
> @EndymionJkb Sorry it's taken so long to get to this. Do you know of the documentation where this is explained? I can't find anything.

With all the recent documentation rework, I believe these details are no longer in the main docs. There's probably only the [in-code documentation](https://github.com/balancer-labs/balancer-v2-monorepo/blob/45a09397c5a79cbe830422cc104dc8dd131cf514/pkg/pool-utils/contracts/BasePoolAuthorization.sol#L34) now.

They are slightly different cases, though. A zero owner means all parameters are fixed: no one has permission to change them. You could say "Fixed parameters". Delegate owner means "ask the Authorizer" if this account can call the permissioned function.

We might need to add documentation to point to here.

**Comment by garethfuller** [comment]
I think if it's the zero address "No owner" probably makes the most sense. But what about the `0xBA1BA1ba1BA1bA1bA1Ba1BA1ba1BA1bA1ba1ba1B` address @EndymionJkb? In that case we use "Delegate owner" and point somewhere?

**Comment by EndymionJkb** [comment]
Yes; I'm just not sure where to point. The docs at that level don't seem to exist anymore, and we probably shouldn't be pointing to code in the UI.

So either we need to have them add this to the documentation so there's somewhere to link to, or maybe just have a tooltip say something like "Permissioned functions validated by the Vault's Authorizer"

**Comment by garethfuller** [comment]
> "Permissioned functions validated by the Vault's Authorizer"
Thanks for this, maybe could be slightly more explicit: "Permissioned functions validated by the Balancer Vault Authorizer"?

@alter-eggo Lets go with that as a starting point:
- `0x0000000000000000000000000000000000000000` - "No owner" (with no external link)
- `0xBA1BA1ba1BA1bA1bA1Ba1BA1ba1BA1bA1ba1ba1B` - "Delegate owner" with tooltip and text mentioned above. (Again, no external link for now)
