### ISSUE TITLE
Add wARRR / WETH ethereum to allowlist

### ISSUE THREAD

**Issue by greywolf42069** [balancer-labs/frontend-v2#2737]
https://app.balancer.fi/#/ethereum/pool/0xb53f8f2907d8e5fed503f8ebce4433fb5c5beae200020000000000000000041e

Website: https://warrr.io/ / https://pirate.black/

**Comment by garethfuller** [comment]
Hi, stable pool approval is usually done through the Maxis in Discord, please ask there first.
