### ISSUE TITLE
NaN values on empty pool table

### ISSUE THREAD

**Issue by simeonkerkola** [balancer-labs/frontend-v2#2786]
Pools without initial liquidity like: `ethereum/pool/0x0371c272fdd28ac13c434f1ef6b8b52ea3e6d8440002000000000000000002a3`
show NaN% token weight

<img width="1637" alt="Screenshot 2023-02-09 at 12 17 32" src="https://user-images.githubusercontent.com/46521087/217755675-67455d2a-a951-4425-8f94-bf3a1763dc09.png">

_Originally posted by @alter-eggo in https://github.com/balancer-labs/frontend-v2/issues/2783#issuecomment-1423800260_

**Comment by garethfuller** [comment]
This was fixed here: https://github.com/balancer-labs/frontend-v2/pull/2790
