### ISSUE TITLE
Decentralize Balancer Frontend V2

### ISSUE THREAD

**Issue by nghianguyen119** [balancer-labs/frontend-v2#768]
**Is your feature request related to a problem? Please describe.**
Did you deploy Balancer on IPFS? I see that you design the frontend that is hostable on IPFS but I don't find the workflow to deploy on it.

**Describe the solution you'd like**
If you are interested in decentralizing the frontend on IPFS, don't hesitate to leave a comment, I'm working on some topics of Crust Network project (decentralized IPFS pinning service) and trying to bring web3 to the real world.

I already deployed your frontend on IPFS, you could find here https://balancer.unstoppabledefi.org
Maybe you use the "Securing With Allowlists" feature on Infura so the content isn't loaded on my domain.

Github workflow to deploy Pancake on IPFS:
1. Build the static web (that requires some modifications on the router and image paths of your source code)
2. Deploy on Pinata (centralized IPFS pinning service)
3. Deploy on Crust Network (decentralized IPFS pinning service)
4. Modify DNS

**Additional context**
How does this feature benefit Balancer users?

Centralized frontend:
- Could be stopped (by external and internal factors)
- Limited bandwidth (pay to use bandwidth)

Hosting app on IPFS:
- Unstoppable
- Unlimited bandwidth, there are currently 200k IPFS nodes (reference: https://protocol.ai/ - creator of IPFS), Pancake frontend could ask these nodes to store partial data on their cache for a short time, the more traffic Pancake has, the faster the frontend is

**Comment by mikemcdonald** [comment]
Cleaning up old issues, please reopen if applicable
